version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'otog'
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_TCP_PORT: 8888
    ports:
      - 8888:8888

  postgres:
    image: postgres:14
    container_name: otog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: otog
      POSTGRES_USER: otog
      POSTGRES_PASSWORD: otog
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
